### ISSUE TITLE
Templates do not respect schema name

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/t4models#19]
In our SQL Server database there are several schemas and and they have the same tables. As result T4 template have to be modified each time when we use such databases.

``` cs
        public ITable<LabelList> LabelLists { get { return this.GetTable<LabelList>(); } }
        public ITable<LabelList> LabelLists { get { return this.GetTable<LabelList>(); } }
```

Maybe it will be good to add optional parameter (schema name) to LoadSqlServerMetadata? And by default try to generate only unique tables.

**Comment by integral-llc** [comment]
I'm having the same issues with duplicate table names in different schemas. Any update on this feature?
Thx

**Comment by sdanyliv** [comment]
@integral-llc, will check. Forgot about this issue.

**Comment by sdanyliv** [comment]
@integral-llc, there is already implemented filter for schemas
```c#
GetSchemaOptions.ExcludedSchemas = new[] { "TestUser", "SYSSTAT" }; // Defines excluded schemas.
GetSchemaOptions.IncludedSchemas = new[] { "TestUser", "SYS" };     // Defines only included schemas.
```
All options are documented on first page https://github.com/linq2db/t4models

**Comment by integral-llc** [comment]
well yes, I could exclude the not-needed schemes, but what to do when I actually need all? Create a different context for each schema or is there a better way?

**Comment by sdanyliv** [comment]
Nothing is perfect. In your case you can include needful schemas and, before generating, correct table's classname.
