### ISSUE TITLE
t4 timeout

### ISSUE THREAD

**Issue by cnrjw1988** [linq2db/t4models#24]
there're too many tables in the sybase and then get an error when T4 running
 Sybase.Data.AseClient.AseException: The command has timed out.
 Sybase.Data.AseClient1.AseCommand.CheckResult(Int32 res)
 Sybase.Data.AseClient1.AseCommand.Execute()
 Sybase.Data.AseClient1.AseCommand._ExecuteReader(CommandBehavior commandBehavior)
 Sybase.Data.AseClient1.AseCommand.ExecuteReader(CommandBehavior commandBehavior)
 Sybase.Data.AseClient.AseCommand.ExecuteDbDataReader(CommandBehavior behavior)
 System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
 System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
 System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
 Sybase.Data.AseClient.AseConnection.GetSchema(String collectionName, String[] restrictionValues)
 Sybase.Data.AseClient.AseConnection.GetSchema(String collectionName)
 LinqToDB.DataProvider.Sybase.SybaseSchemaProvider.GetProcedures(DataConnection dataConnection)
 LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)

**Comment by ili** [comment]
Not reproduced, may be fixed or it is a real connection problem...
