### ISSUE TITLE
How to generate Views as Tables in SQLite

### ISSUE THREAD

**Issue by hoangcuongvn** [linq2db/t4models#26]
I need to generate models for my SQLite databases. Each SQLite database has several views (say vCustomer, vProduct) And I want to have models like vCustomer, vProduct and also properties like MyDB.vCustomer, MyDB.vProduct.

I'd like to know if I could achieve this with Linq2Db?

**Comment by ili** [comment]
Views were not generated for SQLite, now it is fixed.
