### ISSUE TITLE
Is there any CopyMe.XXX.tt.txt on LinqToDB.Templates?

### ISSUE THREAD

**Issue by alexey-tyulkin** [linq2db/t4models#32]
There is  "To create a data model template take a look at one of the CopyMe.XXX.tt.txt file in your LinqToDB.Templates project folder." sentence on readme file.
Is there any CopyMe.XXX.tt.txt on LinqToDB.Templates?

Please write how to i can run the linq2db t4 templates.
Thanks

**Comment by alexey-tyulkin** [comment]
Look at https://github.com/linq2db/t4models/tree/master/NuGet

**Comment by ili** [comment]
@alexey-tyulkin you should use one of linq2db.[database] packages, for ex. [linq2db.SqlServer](https://www.nuget.org/packages/linq2db.sqlserver)

P.S. after installing you may need to update linq2db & linq2db.t4models
