### ISSUE TITLE
LinqToDB.Oracle.Managed.ttinclude not found

### ISSUE THREAD

**Issue by stdray** [linq2db/t4models#33]
I have installed  package linq2db.Oracle.Managed of version 1.0.7.5.

CopyMe.Oracle.Managed.tt.txt contains

```<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.Oracle.Managed.ttinclude" #>```

but file LinqToDB.Oracle.Managed.ttinclude not found in LinqToDB.Templates folder.

**Comment by ili** [comment]
Thanks, we'll fix it.
Just change to 
`<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.Oracle.ttinclude"               #>`
