### ISSUE TITLE
Linq2db, Firebird, T4

### ISSUE THREAD

**Issue by jkarakiz** [linq2db/t4models#34]
When I try to generate model for a Firebird Database through T4 I get the following errors:
Compiling Transformation : could not find type or namespace LinqToDB
Compiling Transformation : could not find type or namespace TableSchema
Compiling Transformation : could not fine type or namespace DataConnection
Linq2db.Firebird version 1.0.7.5

**Comment by ili** [comment]
Please read [this](https://github.com/linq2db/linq2db/issues/505)
