### ISSUE TITLE
version 1.7.5 T4 issue

### ISSUE THREAD

**Issue by integral-llc** [linq2db/t4models#36]
Just updated to latest 1.7.5 version, after which T4 templates stopped to work.
As instructed copy/pasted the demo Template file and got errors about missing types. After adding this line 
```
<#@ assembly name="$(SolutionDir)\packages\linq2db.1.7.5\lib\net45\linq2db.dll" #>
```
in my .TT file everything worked as needed.
Strange, don't remember this to be needed in previous versions.

Please check

**Comment by ili** [comment]
Yes, we'll fix it in next update, thanks!

**Comment by ckhker** [comment]
i have the same error

**Comment by Kempe** [comment]
Me too, I think! 
And there are other issues, when using the latest npgsql.dll (v3.2.0). Please see [[https://github.com/linq2db/linq2db/issues/541].
