### ISSUE TITLE
SQLite: linq2db generates 'double' type for columns/properties of 'float' type

### ISSUE THREAD

**Issue by hoangcuongvn** [linq2db/t4models#39]
Supposing my SQLite db has a table
```sql
CREATE TABLE [MyTable] (
  [ID] INTEGER NOT NULL PRIMARY KEY, 
  [MyColumn] FLOAT)
```
linq2db generates a class like below
```cs
[Table("MyTable")]
public partial class MyTable
{
	[PrimaryKey, Identity   ] public long    ID        { get; set; } // integer
	[Column,        Nullable] public double? MyColumn  { get; set; } // float
}
```
So linq2db generates the wrong type for the property `MyTable.MyColumn`. It should be `float?` instead of `double?`

I note that SQLite only supports 2 numeric types INTEGER and FLOAT. It does not support DOUBLE. So using DOUBLE might cause unexpected faults in calculating.

**Comment by ili** [comment]
According to SQLIte documentation `FLOAT` should be represented as `System.Double`

[SQLite REAL/FLOAT/DOUBLE](https://sqlite.org/datatype3.html):
>REAL. The value is a floating point value, stored as an **8-byte IEEE** floating point number.

[System.Double/double](https://docs.microsoft.com/en-us/dotnet/articles/visual-basic/language-reference/data-types/double-data-type):
> Holds signed **IEEE 64-bit (8-byte)** double-precision floating-point numbers


[System.Single/float](https://docs.microsoft.com/ru-ru/dotnet/articles/visual-basic/language-reference/data-types/single-data-type):
>Holds signed **IEEE 32-bit (4-byte)** single-precision floating-point numbers

**Comment by hoangcuongvn** [comment]
In theory, it seems you are right. In practice, I see real in SQLite works more like float in C#. 

Let's see the sample below:

**Convert 1.04999999 to string through the format "0.0"**
```
select '' || round(1.04999999, 1)
1.0
```
**Convert 1.04999999f (float) to string through the format "0.0"**
```
string.Format("{0:0.0}", 1.04999999f));
1.0
```
**Convert 1.04999999d (double) to string through the format "0.0"**
```
string.Format("{0:0.0}", 1.04999999d));
1.1
```
In my real apps which uses SQLite I see many unexpected faults in calculating if numbers are double  => the result which is calculated in the app (C#) is sometimes different from the one calculated by SQL in SQLite. If they are float, everything is fine

**Comment by ili** [comment]
I see. This may differ, but i think we should follow documentation, or make some additional configuration option.

What you can do now is configure your model

Set this before `GenerateModel();` in your `tt` file:

```t4
GetColumn("MyTable", "MyColumn").Type = "float?";
```

**Comment by hoangcuongvn** [comment]
I actually do a workaround as your recommendation to convert all columns of `double/double?` to `float/float?`. The code is something like underneath.

I agree that we should follow documentation. Is it possible if you allow a way to let linq2db generate float instead of double in SQLite? E.g in a table's declaration, if a column is declared as REAL or DOUBLE or anything except FLOAT => linq2db generates `double`. If it is explicitly declared as FLOAT, linq2db generates `float`.

```
foreach (var t in Tables.Values)
{
	foreach (var c in t.Columns.Values)
	{
		switch (c.Type)
		{
			case "double": c.Type = "float"; break;
			case "double?": c.Type = "float?"; break;
		}
	}
}
```

**Comment by ili** [comment]
I think we can make some kind of option how to treat `REAL` values.
