### ISSUE TITLE
Column type mapping

### ISSUE THREAD

**Issue by dvladimirovich** [linq2db/t4models#51]
I'm using v1.9.0 of linq2db.t4models generator. 
My database is SQLite and I faced with a problem that columns of `database type varchar` are created as columns with `object type`. I expected it to be of `string type`. 
How to resolve this problem?

**Comment by sdanyliv** [comment]
Can you send sample database?

But as workaround, you can correct types in your T4 file.
```
GetColumn("Person", "Gender").Type = "string";
GenerateModel();
```

**Comment by dvladimirovich** [comment]
Currently, I've done like you said. Everything is fine, but I've thought that there could be more convenient way to change type.
