### ISSUE TITLE
Db2 connectivity in .Net

### ISSUE THREAD

**Issue by SipunGit** [linq2db/t4models#53]
As mentioned i have copied CopyMe.DB2.tt.txt file and placed it in my model folder then i have removed the .txt extension and changed the LoadDB2Metadata("MyServer", "50000", "MyDatabase", "MyUser", "TestPassword"); method by providing my connection details.When i save this .tt file it creates all the tables entities but when i call the db object it throws me an error in generated.cs class.The error throws near the default constructor(	public MyDatabaseDB()
		{
			InitDataContext();
		}) like "Object reference not set to an instance of object".This is challenging and i am facing this issue for more than a week now.Please let me know if there is any fix for the same.Also i need to know the way to call a schema which is not default because now it creates entities by targeting to default schema.

**Comment by sdanyliv** [comment]
Duplicate issue from linq2db: https://github.com/linq2db/linq2db/issues/874
