### ISSUE TITLE
TABLE Hints for SQL Server

### ISSUE THREAD

**Issue by DarekDan** [linq2db/t4models#7]
Is it possible to specify table hints for INSERTS and UPDATES? i.e. for BIG TABLE I might prefer ROWLOCK instead of letting SQL Server choose.

**Comment by morphey83** [comment]
Чувак,  вкоряч хинты! ну пожалуйста ! )))

**Comment by ilogman** [comment]
+1 за хинты, по братски впили екстеншн с хинтом

**Comment by grinull** [comment]
+1. Очень надо

**Comment by sdanyliv** [comment]
Already implemented but needs additional coding. See samples here:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/TableFunctionTests.cs
